AyuntamientoMadrid/transparencia

Gemfile
Gemfile.lock

Activada la gema therubyracer para tener un entorno Javascript

activate javascript runtime

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/enquiries.scss
app/views/designs/enquiry_index.html.erb

I've integrated the templates that @isra133 made into the foundation grid system with the real project  structure

Added enquiries index template and base styles

---

app/assets/stylesheets/enquiries.scss
app/views/designs/enquiry_form.html.erb
app/views/designs/enquiry_index.html.erb

Added template integrated with foundation and the project structure.
Related to: https://github.com/AyuntamientoMadrid/transparencia/issues/11

Added Enquiry form

---

app/assets/stylesheets/enquiries.scss
app/views/designs/enquiry_show.html.erb

Added enquiry detail template with foundation grid system!
That's all for us guys! thx!
Related to: https://github.com/AyuntamientoMadrid/transparencia/issues/11
from @isra133 and @basiclines with <3

Added enquiry detail

---

LICENSE

close AyuntamientoMadrid/transparencia#25

Agregado archivo LICENSE con licencia Affero GPL

---

Gemfile
Gemfile.lock
app/controllers/admin/base_controller.rb
app/controllers/admin/dashboard_controller.rb
app/models/administrator.rb
app/views/admin/dashboard/index.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
config/application.rb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/locales/devise.es.yml
config/routes.rb
db/migrate/20151027160228_devise_create_administrators.rb
db/schema.rb
db/seeds.rb
spec/factories.rb
spec/features/admin_spec.rb
spec/rails_helper.rb
spec/spec_helper.rb
spec/support/common_actions.rb

Creates an administrator figure. Inclues:
* Administrator model
* Devise
* /admin namespace which requires login
* tests

Administrators

---

.travis.yml
Gemfile
Gemfile.lock
app/assets/javascripts/app.js.coffee
app/assets/javascripts/application.js
app/assets/javascripts/stat_graphs.js
app/assets/javascripts/stats.js.coffee
app/controllers/admin/api/base_controller.rb
app/controllers/admin/api/stats_controller.rb
app/controllers/admin/stats_controller.rb
app/helpers/stats_helper.rb
app/models/ahoy/data_source.rb
app/models/ahoy/event.rb
app/models/visit.rb
app/views/admin/stats/show.html.erb
app/views/layouts/application.html.erb
config/initializers/ahoy.rb
config/initializers/assets.rb
config/routes.rb
db/migrate/20151103162826_create_visits.rb
db/migrate/20151103162827_create_ahoy_events.rb
db/schema.rb
spec/controllers/admin/api/stats_controller_spec.rb
spec/factories.rb
spec/models/ahoy/data_source_spec.rb
spec/rails_helper.rb
vendor/assets/javascripts/c3.js
vendor/assets/javascripts/c3ext.js
vendor/assets/javascripts/d3.js

This mimics (as much as possible) the setup we did in decide.madrid.es for the visits stats.
Only admins can access visit information. There is no menu to get there just yet, but the stats are available in /admin/stats

Adds visit stats using ahoy

---

app/assets/stylesheets/admin.scss
app/assets/stylesheets/application.scss
app/controllers/admin/base_controller.rb
app/views/admin/_menu.html.erb
app/views/layouts/_head.html.erb
app/views/layouts/admin.html.erb
app/views/layouts/application.html.erb
config/locales/devise.es.yml

Adds an admin layout with a menu for administrative tasks (for now it only shows stats)
@decabeza the style is copied from decide.madrid.es and needs some improvements

[WIP] Admin menu

---

app/assets/stylesheets/admin.scss
app/assets/stylesheets/layout.scss
app/views/admin/stats/show.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/layouts/admin.html.erb
config/locales/devise.es.yml

Algunos estilos para la parte de admin :wink:

Adds styles for admin section

---

app/assets/javascripts/init-foundation.js.coffee
app/assets/stylesheets/layout.scss
app/assets/stylesheets/transparency.scss
app/views/people/_activities_declarations.html.erb
app/views/people/_assets_declarations.html.erb
app/views/people/_contact.html.erb
app/views/people/_diary.html.erb
app/views/people/_menu.html.erb
app/views/people/show.html.erb
config/locales/es.yml

Mejora el menú lateral de user/show haciéndolo “sticky” y responsive.
@decabeza échale un vistazo a esto (en especial los 5px mágicos que le he metido a la clase .fixed-left-sidebar en layout.scss)

Sticky user menu

---

app/assets/stylesheets/layout.scss
app/assets/stylesheets/transparency.scss
app/views/home/index.html.erb
app/views/layouts/application.html.erb
app/views/pages/_menu.html.erb
app/views/pages/_section.html.erb
app/views/people/_activities_declarations.html.erb
app/views/people/_assets_declarations.html.erb
app/views/people/_contact.html.erb
app/views/people/_diary.html.erb
app/views/people/_menu.html.erb
app/views/people/_responsibility.html.erb
app/views/people/index.html.erb
app/views/people/show.html.erb

- Cambiados los estilos para el header.
- Mejorados los estilos para la página del perfil de concejal.
- Nueva versión de la home page.
- Un poco de limpieza del CSS :tada:

Design transparencia

---

app/models/person.rb
app/views/people/_assets_declarations.html.erb
app/views/people/_diary.html.erb
app/views/people/_menu.html.erb
app/views/people/show.html.erb
config/locales/en.yml
config/locales/es.yml
db/migrate/20151126145342_remove_salary_from_person.rb
db/migrate/20151126154044_add_diary_to_people.rb
db/schema.rb
db/seeds.rb
spec/features/people_spec.rb

Añade y quita cosas de la página de people/show para que quede como la vamos a enseñar en la primera versión de producción (el próximo lunes)

People for production

---

app/assets/stylesheets/layout.scss
app/assets/stylesheets/variables.scss
app/views/home/index.html.erb
app/views/layouts/_header.html.erb
config/locales/en.yml
config/locales/es.yml

Nueva home con la sección de declaraciones de bienes de concejales :wink:

Adds new provisional home

---

Gemfile
Gemfile.lock
app/controllers/people_controller.rb
app/models/person.rb
config/initializers/friendly_id.rb
db/migrate/20151127194619_add_slug_to_people.rb
db/schema.rb
spec/models/person_spec.rb

Utiliza el nombre de una person para generar su url.
Por ejemplo: people/manuela-carmena-castrillo

Friendly urls

---

app/views/people/_diary.html.erb
app/views/people/_menu.html.erb
app/views/people/show.html.erb
config/locales/en.yml
config/locales/es.yml

Borra la sección de agendas del perfil de concejales.

removes diaries

---

app/views/layouts/_header.html.erb

updates header's opendata link

---

app/controllers/people_controller.rb
app/models/person.rb

sorts people first by party name, then by internal code

---

Gemfile
Gemfile.lock
app/controllers/people_controller.rb
app/helpers/cache_keys_helper.rb
app/models/activities_declaration.rb
app/models/assets_declaration.rb
app/views/people/_activities_declarations.html.erb
app/views/people/_assets_declarations.html.erb
app/views/people/index.html.erb
app/views/people/show.html.erb
config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb
config/environments/test.rb

Configurada caché en todos los entornos y añadida a people/index y people/show.
Closes #49

Adds cache to people

---

app/assets/stylesheets/layout.scss
app/assets/stylesheets/transparency.scss

Esto mejora los estilos para IE7

Improves styles for IE7

---

app/controllers/subventions_controller.rb
app/models/subvention.rb
app/views/subventions/index.html.erb
config/locales/en.yml
config/locales/es.yml
config/routes.rb
db/dev_seeds.rb
db/migrate/20151202113934_create_subventions.rb
db/schema.rb
spec/factories.rb
spec/features/subventions_spec.rb
spec/rails_helper.rb

Añade subvenciones.
References #4

Subventions

---

app/views/layouts/_header.html.erb
config/locales/en.yml
config/locales/es.yml

Links en el header a subvenciones y contratos

adds subventions and contracts to header's menu

---

config/initializers/i18n_backend.rb

This should speed things up a little bit

adds memoization to i18n backend

---

app/views/people/show.html.erb

adds administrator to cache key in people/show

---

app/models/person.rb
db/migrate/20160401145419_add_sorting_name_to_person.rb
db/schema.rb
lib/sorting_name_calculator.rb
spec/lib/sorting_name_calculator_spec.rb

Ordenación actual
* Del Río Machín
* De Saavedra Lage
Ordenación correcta
*De Saavedra Lage
*Del Río Machín
Ordenación actual
* López-Berini Fernández
* López Cáceres
Ordenación correcta
* López Cáceres
* López-Berini Fernández
Ordenación actual
* Martínez Gobantes
* Martín Frízas
(Esta última no la voy a hacer)

Fix surname sorting

---

Gemfile.lock

https://gemnasium.com/github.com/AyuntamientoMadrid/transparencia/alerts

sec updates gems

---

db/dev_seeds.rb

`bundle exec rake db:dev_seed` throws some errors (apart from some warnings, but that's another topic to fix :D)
- Split Person's name into `first_name` & `last_name`
- Add `job_level` to each Person object creation

Fix dev_seed.rb file (missing and incorrect Person attributes)

---

db/dev_seeds.rb

Correct dev_seed persons names to match the assets images slugs and get councillors images associated
Right now after running `rake db:dev_seed` task and then rails server, on the logs we'll get:
```
[Rollbar] Reporting exception: No route matches [GET] "/images/people/pablo-soto.jpg" @done (06-06-2017 13:05)
[Rollbar] Reporting exception: No route matches [GET] "/images/people/pablo-soto-2.jpg"
[Rollbar] Reporting exception: No route matches [GET] "/images/people/manuela-carmena.jpg"
```
That's because correct names have the second surname, plus there is only one Pablo Soto image.
Just checking the correct "real" names and using them on the rake task

Correct dev_seed persons names to match the assets images slugs
